sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-027
env:
  global:
    - secure: "p+IzM5w5dMpicVyw5kDzpJNmcfvJWAaObezHm67/cDeYyr5Fq6FIVLWnPJRIiSPEDmH6R8qY/ShYusiKN2QwBeiwMUnYm3BDrWJrkFlpt/ZMsOMnOev/YlytPZkZvFidMWmk045Ehbw4ot2P1EOIwutZhzN7U+7e7YErFCDooNqryjZ0gHHg/ueZVx13u/i7/HWEDYpHaQMMnSJdjcU1Q6ul5LLheRvKNISzdwLYM24NmHW/ZfcPSfTEW0ZbyWzy7SphmC1NR1ydx9o/P9s6YPvdGfAYn83BI5IZVUanZIR6pf6oeIumBoz2FKKvRZ41uUJgfWSJew+WRET/04kpky0S9Vj2D8MNEOWiSHBObyvtPzHmE6G4q933vIrmNKEE/6O+mV7UAlv2kudro+/PFAtMYezSuesTcBTn5vr7FfTzVTg/umwiGUGhub17Q5jK9jFReWWFbmI5bRyr4MMzCuaC5lq9iywDE/KVltcHrBGTfU4qJmIBYNS9Ib0zEzjHiQhqt8mao6T1XQoaPkd0XSJVp23mUFtvcyGUeA1dZd654UEfjw4gHdWLRXiKkXEBtCJ/J/cW96W+8he4wM7IZMm7oW+IKjOvRQjL+3V2Z8e4MDeyi/Vx7o7m/P2YWXJ7ycBIHZ3DNIhM0QI6BY+t/NiSxxhM/Sx8hzkJGzRNHrk="
    - secure: "Fw2j9QrFvaDQwtULWQ/pKPrnwwoK4XvhlmoLQUcM0kxbte20YMBAHvsbKYQ7HWdCmhGVPvScPvq9BHULwh1IUWzKDpwC5zyY8wD3spfa1Cb777CAVokZCNP8d7gGzEGBFEF+A52WqvuRpshqziOKfAhdNmvzOB0SDFr7whyJWm03YPua3i0dEASC6RR1pShT4q7jUq+cQ2CbDNblfvrNmZ/Mth0clbQHKCev00CJPHPEu5Ol288AvEIQK0J0oLEPXE6UxqLtudA2qCnThmEnNFf8H+Hi/QPB97uE2r2DrHap89kCoVdn2Tswilc9aZiZD1wcvDlKoOsPp841aehNfrOqXueBrpK+2PxGNFuESBrajVUOsh9n6VsJOtIvah3e868kMFyBcCvp7B8D1r/sa7ozVN6A3UoRkOYBdqjv6SwtDBRlslE9to20B/vBnXR5wZZhAKECeS2Hq1C0wgoBGCPtC3oG4qwF4fyk2d/sG/HMn1G5H1wgW6h++qmPsZnYWsGt6/sBg6Juk89lh697di9eU+vwnaswYAHl7LGlEfDrWfOmSIeBmEdYRpZfAHQaP+812KoHnlr/KREKM8QrbBcbCCWTp5OcFG8Bbvz9+6gAZxG1orKs6bu3MWsqGmVITEJrpFWelSdb5duNCJC2rEdMxrps+g0Gl8zfUDpA/OI="
